DROP TABLE IF EXISTS `MENU`;
CREATE TABLE `MENU` (
  ID INT PRIMARY KEY NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRICE INT
);

INSERT INTO `MENU` (NAME, PRICE)
VALUES ('아메리카노', 4000);

INSERT INTO `MENU` (NAME, PRICE)
VALUES ('카페라떼', 5000);

INSERT INTO `MENU` (NAME, PRICE)
VALUES ('카페모카', 6000);

DROP TABLE IF EXISTS `NUTRITION_FACTS`;
CREATE TABLE NUTRITION_FACTS
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CALORIES        INT,
    SATURATED_FAT   INT,
    MENU_ID         INT  --foreign key
);

INSERT INTO NUTRITION_FACTS(CALORIES, SATURATED_FAT, MENU_ID)
VALUES(3, 4, 1);
INSERT INTO NUTRITION_FACTS(CALORIES, SATURATED_FAT, MENU_ID)
VALUES(4, 2, 1);
INSERT INTO NUTRITION_FACTS(CALORIES, SATURATED_FAT, MENU_ID)
VALUES(2, 2, 2);



-- DROP TABLE IF EXISTS `NUTRITION_FACTS`;
-- CREATE TABLE NUTRITION_FACTS
-- (
--     MENU_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
--     CALORIES        INT,
--     SATURATED_FAT   INT
-- );

-- INSERT INTO NUTRITION_FACTS(CALORIES, SATURATED_FAT)
-- VALUES(3, 4);
-- INSERT INTO NUTRITION_FACTS(CALORIES, SATURATED_FAT)
-- VALUES(4, 2);
-- INSERT INTO NUTRITION_FACTS(CALORIES, SATURATED_FAT)
-- VALUES(2, 2);