DROP TABLE IF EXISTS `MENU`;
CREATE TABLE `MENU` (
  ID INT PRIMARY KEY NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRICE INT
);

INSERT INTO `MENU` (NAME, PRICE)
VALUES ('아메리카노', 4000);

INSERT INTO `MENU` (NAME, PRICE)
VALUES ('카페라떼', 5000);

INSERT INTO `MENU` (NAME, PRICE)
VALUES ('카페모카', 6000);
